# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-08 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
