# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0002_round_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRoundRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain', models.BooleanField(default=False)),
                ('team', models.IntegerField(choices=[(1, 'Team 1'), (2, 'Team 2')])),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbeer.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='team',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='round',
            name='team1',
        ),
        migrations.AddField(
            model_name='round',
            name='team1',
            field=models.ManyToManyField(related_name='team1', to='frisbeer.Player'),
        ),
        migrations.RemoveField(
            model_name='round',
            name='team2',
        ),
        migrations.AddField(
            model_name='round',
            name='team2',
            field=models.ManyToManyField(related_name='team2', to='frisbeer.Player'),
        ),
        migrations.AlterField(
            model_name='round',
            name='winner',
            field=models.IntegerField(choices=[(1, 'Team 1'), (2, 'Team 2')]),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AddField(
            model_name='playerroundrelation',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbeer.Round'),
        ),
    ]
