# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0003_auto_20160526_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, max_length=2500, null=True)),
                ('team1_score', models.IntegerField(default=0)),
                ('team2_score', models.IntegerField(default=0)),
                ('team1', models.ManyToManyField(related_name='team1', to='frisbeer.Player')),
                ('team2', models.ManyToManyField(related_name='team2', to='frisbeer.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='playerroundrelation',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerroundrelation',
            name='round',
        ),
        migrations.RemoveField(
            model_name='round',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='round',
            name='team2',
        ),
        migrations.DeleteModel(
            name='PlayerRoundRelation',
        ),
        migrations.DeleteModel(
            name='Round',
        ),
    ]
