# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-14 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0004_auto_20160604_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
