# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0008_player_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
