# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0009_game_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
