# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0010_auto_20170517_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2)])),
            ],
        ),
       migrations.AddField(
            model_name='gameplayerrelation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbeer.Game'),
        ),
        migrations.AddField(
            model_name='gameplayerrelation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbeer.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='Games', through='frisbeer.GamePlayerRelation', to='frisbeer.Player'),
        ),
    ]
