# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0010_auto_20170517_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image_url', models.CharField(blank=True, max_length=1000)),
            ],
        ),
    ]
