# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0011_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rank',
        ),
        migrations.AddField(
            model_name='player',
            name='rank_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frisbeer.Rank'),
        ),
    ]
