# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 13:18
from __future__ import unicode_literals

from django.db import migrations

from frisbeer.models import GamePlayerRelation


def combine_teams(apps, schema_editor):
    Game = apps.get_model('frisbeer', 'Game')
    for game in Game.objects.all():
        for player in game.team1.all():
            GamePlayerRelation.objects.create(player_id=player.id, game_id=game.id, team=GamePlayerRelation.Team1)
        for player in game.team2.all():
            GamePlayerRelation.objects.create(player_id=player.id, game_id=game.id, team=GamePlayerRelation.Team2)


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0012_auto_20170524_1423'),
    ]

    operations = [
        migrations.RunPython(combine_teams),
    ]
