# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0012_auto_20170520_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rank_link',
            new_name='rank',
        ),
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
