# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0013_auto_20170523_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frisbeer.Rank'),
        ),
    ]
