# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0013_auto_20170526_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2',
        ),
    ]
