# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0015_auto_20170531_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', through='frisbeer.GamePlayerRelation', to='frisbeer.Player'),
        ),
    ]
