# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0015_rank_numerical_value'),
        ('frisbeer', '0018_auto_20170602_1541'),
    ]

    operations = [
    ]
