# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0021_auto_20170804_1320'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameplayerrelation',
            unique_together=set([('player', 'game')]),
        ),
    ]
