# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0023_auto_20170901_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True)),
                ('score_algorithm', models.CharField(choices=[('2017', '2017'), ('2018', '2018')], max_length=255)),
            ],
        ),
    ]
