# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0024_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
