# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 23:58
from __future__ import unicode_literals
from datetime import date

from django.db import migrations, models, utils
import django.db.models.deletion

def create_old_seasons(apps, schema_editor):
    # Add seasons and assign games to them
    Season = apps.get_model('frisbeer', 'Season')
    Game = apps.get_model('frisbeer', 'Game')
    s16 = Season(name="2016", start_date=date(2016, 4, 20), end_date=date(2016, 9, 30))
    s17 = Season(name="2017", start_date=date(2017, 4, 20), end_date=date(2017, 9, 30), score_algorithm='2017')
    s18 = Season(name="2018", start_date=date(2018, 4, 22), end_date=date(2018, 9, 30), score_algorithm='2018')

    for season in s16, s17, s18:
        try:
            season.save()
        except utils.IntegrityError:
            pass  # Season already exists, that's ok

    for game in Game.objects.all():
        for season in Season.objects.all():
            if season.start_date <= game.date.date() <= season.end_date:
                game.season = season
                game.save()
                break

class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0025_auto_20180420_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frisbeer.Season'),
        ),
        migrations.RunPython(
            create_old_seasons,
            lambda x, y: None   # Do nothing in the reverse case, relation is deleted
        )
    ]
