# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0026_game_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='player',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='frisbeer.Rank'),
        ),
    ]
