# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-02 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0027_auto_20180424_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('elo', models.IntegerField(default=1500)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayerRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='season',
            name='score_algorithm',
            field=models.CharField(choices=[('2017', '2017'), ('2018', '2018'), ('elo', 'Best elo')], max_length=255),
        ),
        migrations.AddField(
            model_name='teamplayerrelation',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbeer.Player'),
        ),
        migrations.AddField(
            model_name='teamplayerrelation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbeer.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(through='frisbeer.TeamPlayerRelation', to='frisbeer.Player'),
        ),
        migrations.AddField(
            model_name='team',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frisbeer.Season'),
        ),
        migrations.AlterUniqueTogether(
            name='teamplayerrelation',
            unique_together=set([('player', 'team')]),
        ),
    ]
