# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-26 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0028_auto_20190602_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='virtual',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teamplayerrelation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='frisbeer.Team'),
        ),
    ]
