# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-29 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0029_auto_20190626_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-elo',)},
        ),
        migrations.AddField(
            model_name='player',
            name='season_best',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='season_best',
            field=models.IntegerField(default=0),
        ),
    ]
