# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-06-30 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frisbeer', '0030_auto_20190629_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTeamRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frisbeer.Game')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frisbeer.Team')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(related_name='games', through='frisbeer.GameTeamRelation', to='frisbeer.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='gameteamrelation',
            unique_together=set([('team', 'game'), ('side', 'game')]),
        ),
    ]
